### ISSUE TITLE
add_many with non-ascii content - unicodedecodeerror

### ISSUE THREAD

**Issue by kapaulm** [search5/solrpy#52]
>==========================================================>
<type 'exceptions.UnicodeDecodeError'>
---
'ascii' codec can't decode byte 0xd0 in position 87: ordinal not in range(128)
---
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\solr\core.py", line 334, in wrapper
    return self._update(content, query)
  File "c:\Python27\lib\site-packages\solr\core.py", line 559, in _update
    rsp = self._post(selector, request, self.xmlheaders)
  File "c:\Python27\lib\site-packages\solr\core.py", line 655, in _post
    self.conn.request('POST', url, body.encode('UTF-8'), _headers)
  File "c:\Python27\lib\httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "c:\Python27\lib\httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "c:\Python27\lib\httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "c:\Python27\lib\httplib.py", line 827, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 87: ordinal not in range(128)

**Comment by search5** [comment]
Please let me know what data you have put and I'll check again.
